
import { Globe, Brain, Bot, BarChart, ShoppingCart, MessageSquare } from "lucide-react";
import { Link } from "react-router-dom";

const packages = [
  {
    title: "AI-Powered One-Page Website",
    description: "Perfect for small businesses looking to make a professional online debut with AI tools to enhance engagement and performance.",
    price: "$800",
    timeline: "5-7 days",
    icon: Brain,
    features: [
      "Clean, modern design with AI-powered layout suggestions",
      "Mobile-responsive, with AI-optimized UX for conversions",
      "AI Chatbot integrated for lead generation and customer support",
      "AI-Powered SEO to boost search engine rankings from the start",
      "Domain name included + 1-year web hosting",
      "AI Content Generation for homepage copy"
    ]
  },
  {
    title: "AI-Enhanced 3-Page Website",
    description: "A more comprehensive solution for growing businesses who need AI to streamline and automate processes.",
    price: "$1,200",
    timeline: "7-10 days",
    icon: MessageSquare,
    features: [
      "3 custom pages with AI-driven design and UX suggestions",
      "AI-Powered SEO for increased organic traffic",
      "AI Chatbot for seamless customer support and sales conversion",
      "AI-Generated Content for additional pages",
      "3 months of AI-driven website performance tracking",
      "Mobile-responsive design with AI optimizations"
    ]
  },
  {
    title: "AI-Optimized 5-Page Website",
    description: "For businesses needing advanced features, enhanced AI capabilities, and extensive support for long-term growth.",
    price: "$1,800",
    timeline: "10-14 days",
    icon: Globe,
    features: [
      "5 custom pages with AI-powered UX/UI design for higher conversion rates",
      "Advanced AI SEO to drive sustainable search rankings",
      "Integration of AI-powered product/service recommendations",
      "AI Chatbot for automatic customer interaction and lead capture",
      "AI Content Creation for engaging and on-brand copy across pages",
      "6 months of ongoing AI-based maintenance and support"
    ]
  },
  {
    title: "AI-Powered E-Commerce Website",
    price: "$2,000",
    timeline: "14-20 days",
    description: "For businesses looking to build a full-fledged e-commerce site with AI tools that drive conversions and enhance user experience.",
    icon: ShoppingCart,
    features: [
      "Full-featured online store with AI-driven product recommendations",
      "AI-powered secure checkout process with fraud detection",
      "AI Chatbot to guide users through their shopping journey",
      "Integration with AI inventory management tools",
      "Mobile-responsive design with AI-based user behavior tracking",
      "AI SEO for optimized product descriptions and keywords"
    ]
  }
];

const addOns = [
  {
    title: "AI Content Creation Add-On",
    description: "Monthly blog posts, product descriptions, or landing page copy generated by AI with SEO optimization for content and audience engagement strategies.",
    price: "$500/month",
    icon: Brain,
  },
  {
    title: "AI Marketing Automation Add-On",
    description: "AI-driven email marketing automation and segmentation for personalized messaging with lead nurturing through AI to move leads through the funnel.",
    price: "$600 setup + $150/month",
    icon: BarChart,
  },
  {
    title: "AI Lead Generation Tool Add-On",
    description: "AI-powered lead qualification and segmentation based on visitor behavior with automated follow-ups and lead nurturing based on predefined criteria.",
    price: "$400 setup + $100/month",
    icon: Bot,
  },
  {
    title: "AI Web Performance Monitoring Add-On",
    description: "Ongoing AI-powered analytics for website performance tracking and optimization with actionable AI-driven insights to improve conversion rates.",
    price: "$300/month",
    icon: BarChart,
  },
];

const Features = () => {
  return (
    <section id="features" className="py-16 container-padding bg-neutral-900">
      <div className="max-w-7xl mx-auto">
        <span className="text-sm text-accent tracking-tight">// AI Website Packages</span>
        <h2 className="text-3xl md:text-4xl font-bold mb-4 text-white">
          Transform Your Business with AI-Powered Websites
        </h2>
        <p className="text-neutral-400 mb-12 max-w-3xl">
          At Gridverse, we build cutting-edge websites enhanced with AI capabilities that drive engagement, automate tasks, and optimize performance. Our AI-powered websites help your business stand out, connect with customers, and scale efficiently.
        </p>
        
        {/* Website Packages */}
        <div className="grid md:grid-cols-2 gap-8 mb-16">
          {packages.map((pkg, index) => (
            <div key={index} className="glass-card p-8 rounded-xl">
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-3">
                  <div className="bg-accent/10 p-3 rounded-lg">
                    <pkg.icon className="w-6 h-6 text-accent" />
                  </div>
                  <h3 className="font-semibold text-xl text-white">{pkg.title}</h3>
                </div>
                <div className="text-right">
                  <div className="text-white font-mono bg-accent px-3 py-1 rounded text-sm">
                    {pkg.price}
                  </div>
                  <div className="text-neutral-500 text-xs mt-1">
                    {pkg.timeline}
                  </div>
                </div>
              </div>
              <p className="text-neutral-400 mb-4">{pkg.description}</p>
              <ul className="space-y-2 mb-6">
                {pkg.features.map((feature, idx) => (
                  <li key={idx} className="flex items-start space-x-2 text-neutral-300">
                    <span className="text-accent mt-1">•</span>
                    <span>{feature}</span>
                  </li>
                ))}
              </ul>
              <Link 
                to="/consultation" 
                className="inline-block bg-accent hover:bg-accent/90 text-white px-4 py-2 rounded transition-colors text-sm font-medium"
              >
                Get Started
              </Link>
            </div>
          ))}
        </div>
        
        {/* Add-ons Section */}
        <div>
          <h3 className="text-2xl font-bold mb-6 text-white">AI-Powered Add-Ons</h3>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
            {addOns.map((addon, index) => (
              <div key={index} className="glass-card p-6 rounded-lg">
                <div className="flex items-center gap-3 mb-3">
                  <div className="bg-accent/10 p-2 rounded-lg">
                    <addon.icon className="w-5 h-5 text-accent" />
                  </div>
                  <h4 className="font-semibold text-white">{addon.title}</h4>
                </div>
                <p className="text-neutral-400 text-sm mb-3">{addon.description}</p>
                <div className="text-white font-mono bg-accent/20 px-3 py-1 rounded text-sm inline-block">
                  {addon.price}
                </div>
              </div>
            ))}
          </div>
          
          <div className="text-center mt-12">
            <Link 
              to="/launch" 
              className="bg-white text-neutral-900 px-8 py-3 rounded hover:bg-neutral-200 transition-colors tracking-tight font-medium inline-block"
            >
              View All Packages
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Features;
