// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnjnruqdjizdsdkwoumn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imduam5ydXFkaml6ZHNka3dvdW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3OTExMDQsImV4cCI6MjA1NjM2NzEwNH0.xz4JoEZsOEo1WqZoZmGItrj8cqN_KdbAni7OQT62TX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);